name: Build and Compile

on:
  workflow_dispatch:  # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear cache
        run: sudo rm -rf ~/.gradle/caches/
    
      - name: Checkout repository
        uses: actions/checkout@v3  # 确保 checkout 也使用 v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # 确保 setup-java 使用 v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Apply patches
        run: ./gradlew applyPatches

      - name: Build project
        run: ./gradlew createReobfPaperclipJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # 更新为 v4
        with:
          name: server-core
          path: build/libs/*.jar
